apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{AWS_ACCOUNT_ID}:role/eks-s3-role
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-access-pod
spec:
  serviceAccountName: s3-access-sa
  containers:
  - name: s3-access-pod
    image: amazon/aws-cli
    # command to list s3 buckets
    command: ["sh", "-c", "aws s3 ls"]